### ISSUE TITLE
bfv.fixed.exe crash

### ISSUE THREAD

**Issue by manu1578** [PotatoOfDoom/OriginStubDecrypter#1]
Hi,

I tried bfv.fixed.exe, but crash after load
fixed exe  for 2042  work fine

Thank you

**Comment by PotatoOfDoom** [comment]
hi,

did you try my newest update from today? This one implemented version handling and should've fixed that problem.

**Comment by manu1578** [comment]
Thank you for reply

Yes, i tried with your today update, generated file have all exe section but do nothing when start it.
Previous version from 05/10 generate fixed file but without import section.

I you want, i can upload fixed exe to hoster

**Comment by PotatoOfDoom** [comment]
I just tried it myself and I am getting a crash too if I run it directly. It seems like denuvo/origin does something weird to it because when you 1. Close Origin 2. rename bfv.fixed.exe to bfv.exe, 3. start origin and 4. start the game via origin, the game works completely fine. I created this decrypter mainly for analysis. If only care about running battlefield without launching origin you can just patch the exe directly by editing the "RequireOrigin" flag.

**Comment by manu1578** [comment]
Yes ;), work fine when start from origin. Thank you <3
